package com.mwl.mshop.provider.cmc.mapper;

import com.mwl.mshop.provider.cmc.model.bean.CommodityVO;

public interface CmcCommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    int insert(CommodityVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    int insertSelective(CommodityVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    CommodityVO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    int updateByPrimaryKeySelective(CommodityVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    int updateByPrimaryKey(CommodityVO record);
}