package com.mwl.mshop.provider.cmc.mapper;

import com.mwl.mshop.provider.cmc.model.bean.CmcCommodity;

public interface CmcCommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Mon Mar 04 22:32:49 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Mon Mar 04 22:32:49 CST 2019
     */
    int insert(CmcCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Mon Mar 04 22:32:49 CST 2019
     */
    int insertSelective(CmcCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Mon Mar 04 22:32:49 CST 2019
     */
    CmcCommodity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Mon Mar 04 22:32:49 CST 2019
     */
    int updateByPrimaryKeySelective(CmcCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Mon Mar 04 22:32:49 CST 2019
     */
    int updateByPrimaryKey(CmcCommodity record);
}