package com.mwl.mshop.provider.cmc.mapper;

import com.mwl.mshop.provider.cmc.model.bean.CmcCommodityAttribute;
import com.mwl.mshop.provider.cmc.model.bean.CmcCommodityAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmcCommodityAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    long countByExample(CmcCommodityAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int deleteByExample(CmcCommodityAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int insert(CmcCommodityAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int insertSelective(CmcCommodityAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    List<CmcCommodityAttribute> selectByExample(CmcCommodityAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    CmcCommodityAttribute selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") CmcCommodityAttribute record, @Param("example") CmcCommodityAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByExample(@Param("record") CmcCommodityAttribute record, @Param("example") CmcCommodityAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByPrimaryKeySelective(CmcCommodityAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByPrimaryKey(CmcCommodityAttribute record);
}