package com.mwl.mshop.provider.cmc.mapper;

import com.mwl.mshop.provider.cmc.model.bean.CmcCommodity;
import com.mwl.mshop.provider.cmc.model.bean.CmcCommodityExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

public interface CmcCommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    long countByExample(CmcCommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int deleteByExample(CmcCommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int insert(CmcCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int insertSelective(CmcCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    List<CmcCommodity> selectByExample(CmcCommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    CmcCommodity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") CmcCommodity record, @Param("example") CmcCommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByExample(@Param("record") CmcCommodity record, @Param("example") CmcCommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByPrimaryKeySelective(CmcCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByPrimaryKey(CmcCommodity record);
}