package com.mwl.mshop.provider.cmc.mapper;

import com.mwl.mshop.provider.cmc.model.bean.CmcCommodityAttributeCategory;
import com.mwl.mshop.provider.cmc.model.bean.CmcCommodityAttributeCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmcCommodityAttributeCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    long countByExample(CmcCommodityAttributeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int deleteByExample(CmcCommodityAttributeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int insert(CmcCommodityAttributeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int insertSelective(CmcCommodityAttributeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    List<CmcCommodityAttributeCategory> selectByExample(CmcCommodityAttributeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    CmcCommodityAttributeCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") CmcCommodityAttributeCategory record, @Param("example") CmcCommodityAttributeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByExample(@Param("record") CmcCommodityAttributeCategory record, @Param("example") CmcCommodityAttributeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByPrimaryKeySelective(CmcCommodityAttributeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByPrimaryKey(CmcCommodityAttributeCategory record);
}