package com.mwl.mshop.provider.cmc.mapper;

import com.mwl.mshop.provider.cmc.model.bean.CmcCommodityCategory;
import com.mwl.mshop.provider.cmc.model.bean.CmcCommodityCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmcCommodityCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    long countByExample(CmcCommodityCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int deleteByExample(CmcCommodityCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int insert(CmcCommodityCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int insertSelective(CmcCommodityCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    List<CmcCommodityCategory> selectByExampleWithBLOBs(CmcCommodityCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    List<CmcCommodityCategory> selectByExample(CmcCommodityCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    CmcCommodityCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") CmcCommodityCategory record, @Param("example") CmcCommodityCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CmcCommodityCategory record, @Param("example") CmcCommodityCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByExample(@Param("record") CmcCommodityCategory record, @Param("example") CmcCommodityCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByPrimaryKeySelective(CmcCommodityCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CmcCommodityCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_category
     *
     * @mbg.generated Sun Mar 10 15:17:45 CST 2019
     */
    int updateByPrimaryKey(CmcCommodityCategory record);
}