package com.mwl.mshop.provider.cmc.mapper;

import com.mwl.mshop.provider.cmc.model.bean.CommodityAttributeCategoryVO;

public interface CmcCommodityAttributeCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    int insert(CommodityAttributeCategoryVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    int insertSelective(CommodityAttributeCategoryVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    CommodityAttributeCategoryVO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    int updateByPrimaryKeySelective(CommodityAttributeCategoryVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmc_commodity_attribute_category
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    int updateByPrimaryKey(CommodityAttributeCategoryVO record);
}