server:
  port: 7071
spring:
  application:
    name: eureka-consume
  security:
    user:
      name: admin
      password: 123123
eureka:
  client:
    service-url:
      defaultZone: http://admin:123123@localhost:8761/eureka/
  instance:
    hostname: localhost
# 服务降级
feign:
  hystrix:
    enabled: true