server:
  port: 7070
spring:
  application:
    name: eureka-client
  security:
    user:
      name: admin
      password: 123123

eureka:
  client:
    service-url:
      defaultZone: http://admin:123123@localhost:8761/eureka/
