spring:
  application:
    name: mshop-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MaWenlong1/config-repo
          username: mwljndx@163.com
          password: m89676378
#  rabbitmq:
#    host: 111.231.228.108
eureka:
  client:
    service-url:
      defaultZone: http://admin:123123@localhost:8761/eureka/
server:
  port: 6062
management:
  endpoints:
    web:
      exposure:
        include: "*"