package com.mwl.mshop.provider.cmc.model.dto;

import lombok.Data;

import java.math.BigDecimal;

/**
 * @author mawenlong
 * @date 2019/03/05
 *
 * 商品信息
 */
@Data
public class CommodityVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.id
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.brand_id
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private BrandVO brandVO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.commodity_category_id
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Long commodityCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.commodity_attribute_category_id
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Long commodityAttributeCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.name
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.pic
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.status
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.sale
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer sale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.price
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.gift_growth
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer giftGrowth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.gift_point
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer giftPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.sub_title
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String subTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.description
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.stock
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.low_stock
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer lowStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.unit
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.weight
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private BigDecimal weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.keywords
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.album_pics
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String albumPics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.detail_title
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String detailTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity.detail_html
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String detailHtml;
}
