spring:
  application:
    name: mshop-gateway
server:
  port: 5050
# 引入eureka后自动配置以下
#zuul:
#  routes:
#    eureka-consume: /**
#    api-b-url:
#      path: /api-b-url/**
#      serviceId: eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://admin:123123@localhost:8761/eureka/
zuul:
  sensitive-headers: