package com.mwl.mshop.provider.cmc.model.bean;

import lombok.Data;

@Data
public class CmcBrand {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cmc_brand.id
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cmc_brand.name
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cmc_brand.first_letter
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String firstLetter;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cmc_brand.sort
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cmc_brand.factory_status
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer factoryStatus;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cmc_brand.show_status
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer showStatus;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cmc_brand.commodity_count
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer commodityCount;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cmc_brand.commodity_comment_count
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer commodityCommentCount;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cmc_brand.logo
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cmc_brand.big_pic
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String bigPic;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cmc_brand.brand_story
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String brandStory;

}