package com.mwl.mshop.provider.cmc.model.bean;

import lombok.Data;

@Data
public class CmcCommodityAttributeValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute_value.id
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute_value.commodity_id
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Long commodityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute_value.commodity_attribute_id
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Long commodityAttributeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute_value.value
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String value;
}