package com.mwl.mshop.provider.cmc.model.bean;

import lombok.Data;

@Data
public class CmcCommodityAttribute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute.id
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute.commodity_attribute_category_id
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Long commodityAttributeCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute.name
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute.select_type
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer selectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute.input_type
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer inputType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute.input_list
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String inputList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute.sort
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute.filter_type
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer filterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute.search_type
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer searchType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute.related_status
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer relatedStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute.hand_add_status
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer handAddStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute.type
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer type;

}