package com.mwl.mshop.provider.cmc.model.bean;

import lombok.Data;

@Data
public class CmcCommodityAttributeCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute_category.id
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute_category.name
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute_category.attribute_count
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer attributeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmc_commodity_attribute_category.param_count
     *
     * @mbg.generated Tue Mar 05 13:17:59 CST 2019
     */
    private Integer paramCount;


}